name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    paths-ignore:
      - "README.md"
      - "images/"
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
